### ISSUE TITLE
UnsatisfiableDependenciesException with Sonarqube 7.6

### ISSUE THREAD

**Issue by pucojazu** [Inform-Software/sonar-groovy#1]
Hi,

when I try to use the 1.6-SNAPSHOT with the current Sonarqube 7.6 I get the following Exception:

`org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: org.sonar.plugins.groovy.codenarc.CodeNarcSensor has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public org.sonar.plugins.groovy.codenarc.CodeNarcSensor(org.sonar.api.profiles.RulesProfile,org.sonar.plugins.groovy.foundation.GroovyFileSystem)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@18c0d600:90<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@4397b95c:441<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@170ad400:47`

The reason is that the class RulesProfile was deprecated and has been removed now, see https://community.sonarsource.com/t/unsatisfied-dependency-in-sq-7-6/6244

**Comment by TobiX** [comment]
Getting rid of deprecated classes is certainly on my roadmap. For my first release I want to stay compatible with the current LTS (6.7) and it seems those classes were deprecated a long time ago, so that seems possible here... As always: Pull requests welcome!

**Comment by Hydragyrum** [comment]
Hi all,

I submitted #4 to fix this. Preliminary testing seems to not crash (Tested on a sonar docker container)

**Comment by TobiX** [comment]
This should be fixed now that I merged @Hydragyrum's changes. Please test!

**Comment by pucojazu** [comment]
Thank you, I think this issue is fixed.
I tried to test it with Sonarqube 7.7, but there is another problem now: #6
