### ISSUE TITLE
Unable to register token in groovy file 

### ISSUE THREAD

**Issue by liuwei-tianshu** [Inform-Software/sonar-groovy#102]
error log:
[log.txt](https://github.com/Inform-Software/sonar-groovy/files/7673714/log.txt)

AdminLoginPage.groovy:
[AdminLoginPage.groovy.txt](https://github.com/Inform-Software/sonar-groovy/files/7673730/AdminLoginPage.groovy.txt)

**Comment by liuwei-tianshu** [comment]
fixed by removing line 27 in AdminLoginPage.groovy.

**Comment by TobiX** [comment]
Interesting. Maybe the parser chokes on the "fancy" quotes?
