### ISSUE TITLE
Recent versions of SonarQube have deprecated JaCoCo .exec binary format

### ISSUE THREAD

**Issue by michelzanini** [Inform-Software/sonar-groovy#11]
Recent versions of SonarJava plugin for SonarQube have deprecated JaCoCo .exec binary format.
Now they are support the XML format, using sonar.coverage.jacoco.xmlReportPaths.
I am not really sure, but probably something Groovy plugin needs to consider.

**Comment by TobiX** [comment]
AFAIK, there is nothing I need to do in the Groovy plugin (well, except maybe deprecating the old properties), since the new XML-based JaCoCo plugin automatically supports all registered languages.

**Comment by TobiX** [comment]
Mostly done in 1.7, remaining JaCoCo support will probably be dropped in 1.8
