### ISSUE TITLE
No codenarc reports published using sonar.groovy.codenarc.reportPaths

### ISSUE THREAD

**Issue by philbert** [Inform-Software/sonar-groovy#12]
Fist of all thanks @TobiX for keeping this project alive.

I've been trying to get a project to publish a codenarc report to sonarqube with a customized  ruleset. It appears that the report is being correct read from the sonar-scanner and uploaded to the server:

```
07:01:38.123 INFO: Sensor CodeNarc [groovy]
07:01:38.184 INFO: Sensor CodeNarc [groovy] (done) | time=61ms
07:01:38.185 INFO: Sensor GroovySensor [groovy]
```

We can read the html version of the report just fine, however the xml results are not being read by the sonar server. I actually get the same issues displayed on the server even if I configure ```sonar.groovy.codenarc.reportPaths``` incorrectly (which I've confirmed throws an error in the debug logs of the sonar-scanner).

There is only 3 type of issues that are shown on the server and none of them appear to come from our .xml report. The 2nd and 3rd issue only appear when I also publish a jacoco coverage report. I'm not sure why only the 1st one is always seen.
* Source files should have a sufficient density of comment lines
* Lines should have sufficient coverage by tests
* Branches should have sufficient coverage by tests

We're currently using codenarc 0.25.2 that is in-build with gradle 4.4, which looks like it is the latest version supported by the sonar-groovy plugin.

The only thing that I can guess is causing a problem is our customised ruleset... which is basically the whole point of this exercise because it is not possible to customize rules on the sonar server.

Any advice?

**Comment by TobiX** [comment]
Could you try with release 1.6, which comes with codenarc 1.4

**Comment by philbert** [comment]
Thanks for getting back to me on this... although I think that I will close this issue, as it seems to have become moot in recent days for a few reasons: 

1. I discovered that it is actually possible to modify the rules in sonarqube to (more or less) match what we had in our customized rule set. 
2. Although we don't yet have a solution to running a "local" sonar-scan (which unfortunately seems to require running a sonarqube server on localhost), the problem is significantly reduced by the improved support for pull-requests in Sonarqube (since 7.7 I believe). This means you only need to worry about issues related to your changes, rather than all the issues in the repository. 
3. My use case is in a large enterprise where we want server-side configuration and control over projects. Local configurations lead to too much variability and allow sloppiness where we want to leverage Sonarqube as tool to drive improvements to code quality.
