### ISSUE TITLE
Roadmap for SonarQube plugin marketplace registration

### ISSUE THREAD

**Issue by roded** [Inform-Software/sonar-groovy#2]
Hi,
Thanks for forking this plugin.
We're using SonarQube via docker and are awaiting the availability of the sonar-groovy plugin reboot in the marketplace before bumping the SonarQube version to latest.
Is there a plan to submit the plugin to the marketplace with the previous plugin's signature?

**Comment by TobiX** [comment]
Yes, that's the plan and SonarSource has shown willingness to allow a "takeover" of the previous plugin's signature.

**Comment by ToineSiebelink** [comment]
Hi, is there any update on the MarketPlace reboot for this plugin?

**Comment by michelzanini** [comment]
Hi, 

I see there are many commits done here after the fork, but, there are no new releases.
Is 1.6 near to be released? Will it support latest Sonar 7.7?

Thanks.

**Comment by TobiX** [comment]
@michelzanini The current [test builds](https://ci.appveyor.com/project/TobiX/sonar-groovy/build/artifacts) already support SonarQube 7.7 - I was thinking about updating CodeNarc to the latest version before preparing a "proper" release.

**Comment by cmhdave** [comment]
Any new status update on SonarSource allowing a takeover?  Our company won't make the switch until the plugin is "official" which is unfortunate but my hands are tied.

**Comment by cmhdave** [comment]
Just a follow-up to my previous post.  Has this been requested in the Sonar Community Forum?  I searched back as far as 2018 and didn't see anything for Groovy.

https://community.sonarsource.com/t/sonarqubecommunity-repos-are-plugins-in-search-of-maintainers/2551

**Comment by TobiX** [comment]
Released 1.6
