### ISSUE TITLE
Upgrade CodeNarc to 1.5

### ISSUE THREAD

**Issue by agabrys** [Inform-Software/sonar-groovy#26]
CodeNarc 1.5 has been released on 24 Nov 2019 (read [changelog](https://github.com/CodeNarc/CodeNarc/blob/master/CHANGELOG.md#version-15----nov-2019)).

Could you bump version from 1.4 to 1.5?

**Comment by TobiX** [comment]
On my plan 😄

**Comment by TobiX** [comment]
Since CodeNarc switched the structure of their project (Maven to Gradle & documentation from apt to markdown), this will probably take some time, since this plugin "parses" the documentation to provide rule documentation in SonarQube...
