### ISSUE TITLE
Re-house plugin at binaries.sonarsource

### ISSUE THREAD

**Issue by dbeezt** [Inform-Software/sonar-groovy#28]
I work in a fairly locked-down network, which makes it troublesome to access external packages. Our main access method is the use of proxies, of which our sonar one points to https://binaries.sonarsource.com/. The latest plugin available within this proxy-able location is [1.4](https://binaries.sonarsource.com/Distribution/sonar-groovy-plugin/). 

I wondered whether it might be possible to resume uploading versions of this plugin to that location? It's possible for me to workaround the network and manually bring it in with my own scans, etc., but the addition of this plugin back to these sort of official repos might aid those such as myself who work in restricted environments.

I'd guess that there might be some credentials needed to upload this plugin to binaries.sonarsource, which sonar would be understandably reluctant to make available. However, I feel that given this is the [official plugin](https://www.sonarplugins.com/groovy) as listed on their marketplace for Groovy/Sonar interaction, the plugin should be made available in a more official manner.

**Comment by TobiX** [comment]
That's not possible for me. As with all community plugins, they are hosted wherever the author deems convenient. If you want SonarSource to proxy the plugins, please take it up with them.

See
- https://docs.sonarqube.org/latest/extend/deploying-to-marketplace/
- https://github.com/SonarSource/sonar-update-center-properties

**Comment by dbeezt** [comment]
Excuse the invalid-ness of this request but I wasn't sure where else to turn. Thanks for the response and I appreciate the resources - I'll check em out now!

**Comment by TobiX** [comment]
No problem - you probably will have this problem with all other 3rd-party plugins, too. This plugin is only special in the sense that it was "official" a long time ago and was dropped by SonarSource and picked up by the community...
