### ISSUE TITLE
Question: Gradle DSL support?

### ISSUE THREAD

**Issue by alixwar** [Inform-Software/sonar-groovy#29]
Hi,

is the analysis of build.gradle files (Groovy) supported? If not, is it in the roadmap?

Regards
Alix

**Comment by TobiX** [comment]
Shouldn't it be possible to manually add them?

You need to make sure the scanner you are using sees them as code and then add `.gradle` as supported extension:
![grafik](https://user-images.githubusercontent.com/78534/93573704-c513ab80-f997-11ea-8f8f-3d4e16699051.png)

**Comment by alixwar** [comment]
@TobiX Yes, it is possible. But I'm getting all sorts of odd violations because the plugin doesn't seem to be versed in Gradle

**Comment by TobiX** [comment]
Maybe ask the CodeNarc developers (this plugin is just a small layer on top of that) if they consider Gradle analysis in scope for their analyser? I'm not sure what I'm able to change to support Gradle files better.

**Comment by alixwar** [comment]
I wasn't aware of the underlying library. I will move my request to https://github.com/CodeNarc/CodeNarc
