### ISSUE TITLE
Update SonarSource redirect link

### ISSUE THREAD

**Issue by CCFenner** [Inform-Software/sonar-groovy#8]
- [ ] Update the redirect link http://redirect.sonarsource.com/plugins/groovy.html to point to this repository `README`. 
- [ ] Set `url` in `pom.xml` back to SonarSource link

see
https://github.com/Inform-Software/sonar-groovy/blob/master/sonar-groovy-plugin/pom.xml#L16-L20

**Comment by TobiX** [comment]
This is fixed with 0999d2bc9878f80a04bfc5528959b4e6898bfa38 and 6644a0fb61f741d5b4abd524b8ada5942b45cdf6
